In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("test_scores.csv")

In [3]:
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [4]:
x=np.array(df.math)

In [5]:
x

array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67], dtype=int64)

In [6]:
y=np.array(df.cs)

In [7]:
y

array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73], dtype=int64)

In [8]:
import math

In [9]:
def gradient_descent(x,y):
    m_curr=b_curr=0
    iterations=10000
    n=len(x)
    learning_rate=0.00002
    cost_previous=0
    for i in range(iterations):
        y_predicted=m_curr*x+b_curr
        cost = (1/n)*sum([value**2 for value in (y-y_predicted)])
        m_deri=-(2/n)*sum(x*(y-y_predicted))
        b_deri=-(2/n)*sum(y-y_predicted)
        m_curr=m_curr-learning_rate*m_deri
        b_curr=b_curr-learning_rate*b_deri
        if math.isclose(cost, cost_previous, rel_tol=1e-20):
            break
        cost_previous = cost
        print("m {},b {},cost {},iterations {}".format(m_curr,b_curr,cost,i))
        
        
        

In [10]:
gradient_descent(x,y)

m 0.19783600000000004,b 0.0027960000000000003,cost 5199.1,iterations 0
m 0.358202304128,b 0.005063270368,cost 3427.1133014146017,iterations 1
m 0.48819558675989866,b 0.006901951280555265,cost 2262.7832239523723,iterations 2
m 0.5935684284372227,b 0.008393216594681594,cost 1497.729778255618,iterations 3
m 0.6789838841536092,b 0.009602866025233548,cost 995.0314573648972,iterations 4
m 0.7482218369922624,b 0.010584236972134094,cost 664.7204139555688,iterations 5
m 0.804346268858218,b 0.011380564854211883,cost 447.6809274080213,iterations 6
m 0.8498408505179355,b 0.012026896401228556,cost 305.0694716371467,iterations 7
m 0.8867188511966752,b 0.012551640572788583,cost 211.36289471465685,iterations 8
m 0.9166122315504622,b 0.012977825736768155,cost 149.79054397304932,iterations 9
m 0.940843862633698,b 0.01332411874103585,cost 109.33282466617912,iterations 10
m 0.960486066760105,b 0.013605650975328967,cost 82.74902465381011,iterations 11
m 0.9764080708590054,b 0.013834687978906954,cost 65.281

m 1.0444663583593845,b 0.02092505524662612,cost 31.810505138717915,iterations 1419
m 1.0444662969928324,b 0.02092940413487998,cost 31.810504192884903,iterations 1420
m 1.0444662356264214,b 0.020933753013149738,cost 31.810503247056246,iterations 1421
m 1.044466174260151,b 0.020938101881435415,cost 31.810502301231935,iterations 1422
m 1.0444661128940216,b 0.020942450739737033,cost 31.810501355411947,iterations 1423
m 1.044466051528033,b 0.020946799588054617,cost 31.810500409596315,iterations 1424
m 1.0444659901621853,b 0.02095114842638819,cost 31.810499463785057,iterations 1425
m 1.0444659287964786,b 0.020955497254737776,cost 31.81049851797808,iterations 1426
m 1.0444658674309129,b 0.020959846073103396,cost 31.810497572175468,iterations 1427
m 1.044465806065488,b 0.02096419488148507,cost 31.81049662637723,iterations 1428
m 1.0444657447002037,b 0.020968543679882826,cost 31.81049568058329,iterations 1429
m 1.0444656833350605,b 0.020972892468296686,cost 31.810494734793725,iterations 1430
m 

m 1.0443840699080673,b 0.02675662419311845,cost 31.809238790547898,iterations 2762
m 1.0443840087304317,b 0.02676095969335637,cost 31.809237850529414,iterations 2763
m 1.0443839475529364,b 0.026765295183640923,cost 31.80923691051524,iterations 2764
m 1.0443838863755817,b 0.026769630663972133,cost 31.809235970505366,iterations 2765
m 1.0443838251983675,b 0.02677396613435002,cost 31.809235030499877,iterations 2766
m 1.0443837640212936,b 0.02677830159477461,cost 31.809234090498634,iterations 2767
m 1.0443837028443603,b 0.026782637045245923,cost 31.80923315050171,iterations 2768
m 1.0443836416675674,b 0.026786972485763984,cost 31.809232210509123,iterations 2769
m 1.044383580490915,b 0.026791307916328812,cost 31.809231270520854,iterations 2770
m 1.0443835193144029,b 0.026795643336940435,cost 31.80923033053689,iterations 2771
m 1.0443834581380314,b 0.026799978747598874,cost 31.80922939055725,iterations 2772
m 1.0443833969618002,b 0.02680431414830415,cost 31.80922845058191,iterations 2773
m 1

m 1.0443134422419031,b 0.031761823564021456,cost 31.808155005513072,iterations 3918
m 1.0443133812264134,b 0.03176614757340853,cost 31.80815407047085,iterations 3919
m 1.0443133202110635,b 0.031770471572868615,cost 31.808153135432917,iterations 3920
m 1.0443132591958537,b 0.03177479556240174,cost 31.8081522003993,iterations 3921
m 1.044313198180784,b 0.03177911954200792,cost 31.808151265369943,iterations 3922
m 1.0443131371658545,b 0.03178344351168719,cost 31.808150330344894,iterations 3923
m 1.044313076151065,b 0.031787767471439556,cost 31.808149395324133,iterations 3924
m 1.0443130151364157,b 0.03179209142126505,cost 31.808148460307645,iterations 3925
m 1.0443129541219065,b 0.0317964153611637,cost 31.80814752529549,iterations 3926
m 1.0443128931075372,b 0.03180073929113552,cost 31.80814659028762,iterations 3927
m 1.044312832093308,b 0.03180506321118053,cost 31.808145655284047,iterations 3928
m 1.0443127710792188,b 0.031809387121298764,cost 31.808144720284727,iterations 3929
m 1.04431

m 1.0442369779220333,b 0.037180651432724164,cost 31.80698489938878,iterations 5173
m 1.0442369170820889,b 0.03718496300165918,cost 31.80698396971917,iterations 5174
m 1.0442368562422841,b 0.037189274560695776,cost 31.806983040053844,iterations 5175
m 1.044236795402619,b 0.03719358610983396,cost 31.806982110392745,iterations 5176
m 1.0442367345630936,b 0.03719789764907377,cost 31.806981180735974,iterations 5177
m 1.0442366737237079,b 0.03720220917841522,cost 31.806980251083445,iterations 5178
m 1.0442366128844618,b 0.037206520697858333,cost 31.806979321435144,iterations 5179
m 1.0442365520453554,b 0.037210832207403136,cost 31.806978391791166,iterations 5180
m 1.0442364912063886,b 0.03721514370704965,cost 31.80697746215143,iterations 5181
m 1.0442364303675615,b 0.037219455196797896,cost 31.80697653251595,iterations 5182
m 1.0442363695288743,b 0.0372237666766479,cost 31.806975602884776,iterations 5183
m 1.0442363086903268,b 0.03722807814659968,cost 31.806974673257834,iterations 5184
m 1.0

m 1.044161400918046,b 0.042536597528006086,cost 31.80583168440618,iterations 6417
m 1.04416134025161,b 0.04254089680085195,cost 31.805830760031654,iterations 6418
m 1.0441612795853132,b 0.04254519606382761,cost 31.805829835661342,iterations 6419
m 1.0441612189191558,b 0.0425494953169331,cost 31.805828911295244,iterations 6420
m 1.0441611582531376,b 0.04255379456016844,cost 31.805827986933423,iterations 6421
m 1.0441610975872586,b 0.04255809379353365,cost 31.805827062575858,iterations 6422
m 1.044161036921519,b 0.04256239301702875,cost 31.805826138222535,iterations 6423
m 1.0441609762559187,b 0.04256669223065377,cost 31.805825213873444,iterations 6424
m 1.0441609155904577,b 0.04257099143440873,cost 31.805824289528573,iterations 6425
m 1.0441608549251358,b 0.04257529062829365,cost 31.805823365187997,iterations 6426
m 1.0441607942599533,b 0.042579589812308555,cost 31.805822440851657,iterations 6427
m 1.0441607335949101,b 0.04258388898645347,cost 31.805821516519536,iterations 6428
m 1.0441

m 1.0440808980056764,b 0.04824162996403589,cost 31.804606928455303,iterations 7746
m 1.0440808375240576,b 0.04824591613936616,cost 31.804606009704273,iterations 7747
m 1.0440807770425777,b 0.0482502023048563,cost 31.804605090957494,iterations 7748
m 1.0440807165612367,b 0.04825448846050634,cost 31.804604172214923,iterations 7749
m 1.0440806560800344,b 0.04825877460631629,cost 31.804603253476554,iterations 7750
m 1.044080595598971,b 0.04826306074228619,cost 31.80460233474242,iterations 7751
m 1.0440805351180464,b 0.04826734686841604,cost 31.804601416012503,iterations 7752
m 1.0440804746372607,b 0.04827163298470589,cost 31.8046004972868,iterations 7753
m 1.0440804141566138,b 0.048275919091155736,cost 31.80459957856532,iterations 7754
m 1.0440803536761059,b 0.048280205187765615,cost 31.804598659848057,iterations 7755
m 1.0440802931957367,b 0.04828449127453555,cost 31.80459774113499,iterations 7756
m 1.0440802327155065,b 0.04828877735146556,cost 31.804596822426163,iterations 7757
m 1.04408

m 1.04402157188719,b 0.05244591798674175,cost 31.80370674384547,iterations 8728
m 1.044021511541771,b 0.052450194509939714,cost 31.80370582922771,iterations 8729
m 1.0440214511964907,b 0.0524544710233197,cost 31.803704914614144,iterations 8730
m 1.044021390851349,b 0.05245874752688175,cost 31.8037040000048,iterations 8731
m 1.0440213305063457,b 0.052463024020625866,cost 31.803703085399622,iterations 8732
m 1.044021270161481,b 0.05246730050455208,cost 31.803702170798637,iterations 8733
m 1.044021209816755,b 0.05247157697866042,cost 31.803701256201887,iterations 8734
m 1.0440211494721672,b 0.05247585344295091,cost 31.803700341609314,iterations 8735
m 1.044021089127718,b 0.05248012989742356,cost 31.803699427020945,iterations 8736
m 1.0440210287834073,b 0.0524844063420784,cost 31.803698512436785,iterations 8737
m 1.0440209684392352,b 0.05248868277691545,cost 31.80369759785682,iterations 8738
m 1.0440209080952016,b 0.05249295920193474,cost 31.803696683281075,iterations 8739
m 1.044020847751

m 1.043952747600422,b 0.05732331654093369,cost 31.80266498162975,iterations 9870
m 1.0439526874130087,b 0.05732758186668373,cost 31.80266407179532,iterations 9871
m 1.0439526272257336,b 0.0573318471826415,cost 31.802663161965043,iterations 9872
m 1.0439525670385967,b 0.05733611248880703,cost 31.80266225213896,iterations 9873
m 1.043952506851598,b 0.05734037778518035,cost 31.802661342317034,iterations 9874
m 1.0439524466647374,b 0.05734464307176147,cost 31.8026604324993,iterations 9875
m 1.043952386478015,b 0.05734890834855042,cost 31.802659522685747,iterations 9876
m 1.0439523262914308,b 0.057353173615547225,cost 31.802658612876357,iterations 9877
m 1.0439522661049847,b 0.0573574388727519,cost 31.802657703071176,iterations 9878
m 1.0439522059186768,b 0.057361704120164475,cost 31.80265679327014,iterations 9879
m 1.043952145732507,b 0.057365969357784964,cost 31.802655883473285,iterations 9880
m 1.0439520855464755,b 0.0573702345856134,cost 31.802654973680603,iterations 9881
m 1.0439520253

In [11]:
from sklearn.linear_model import LinearRegression as lr

In [12]:
lr=lr()

In [13]:
model=lr.fit(df[['math']],df.cs)

In [14]:
model.coef_

array([1.01773624])

In [15]:
model.intercept_

1.9152193111568891