In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("canada_per_capita_income.csv")

In [3]:
df.head()

year    percapita
0  1970  3399.299037
1  1971  3768.297935
2  1972  4251.175484
3  1973  4804.463248
4  1974  5576.514583

In [4]:
from sklearn.linear_model import LinearRegression as LR

In [5]:
model=LR()

In [6]:
model.fit(df[['year']],df.percapita)

LinearRegression()

In [7]:
model.predict([[2020]])

array([41288.69409442])

In [8]:
import pickle

In [9]:
#Saving model in the form of binary file Using Pickling method
with open('Linear-regression_saved','wb') as f:
    pickle.dump(model,f)

In [10]:
#Loading Model from saved file
with open('Linear-regression_saved','rb') as f:
    Loaded_model=pickle.load(f)

In [11]:
Loaded_model.predict([[2020]])

array([41288.69409442])

In [12]:
#saving file in the form of binary file using joblib method
import joblib
from joblib import dump,load

In [13]:
dump(model,'Regression_saved')

['Regression_saved']

In [14]:
L_model=load("Regression_saved")

In [15]:
L_model.predict([[2020]])

array([41288.69409442])